layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "Adventurous, nature-loving, curious, and always up for a new challenge and never afraid to push boundaries."
about: "ABOUT ME"
email: ftm.haghpanah@gmail.com


social_media:
  linkedin: fateme-sadat-haghpanah-b2b59a90
  scholar: _QKNDs0AAAAJ&hl
  github: ftmhghpnh
  twitter: fatemehghpanah

  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of Toronto"
    company_url: ""
    role: "Graduate Research Assistant"
    start: "Jan 2021"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Affiliated with , <a href=\"https://vectorinstitute.ai\">Vector Institute for Artificial Intelligence</a>, <a href=\"https://www.uhn.ca/\">University Health Network</a>, and <a href=\"https://www.sickkids.ca/\">SickKids, the Hospital for Children</a>.
      <li> To assist diagnosis of neurodevelopmental impairments, I developed  a generalized novel algorithm to detect cerebral microbleeds (CMB) in MRI modality from pre-term infants' brains. </li>
      <li> To expedite the diagnosis of brain tumors in children in hospital emergency rooms, where wait times can be lengthy, I developed a machine learning model for identifying signs of raised intracranial pressure (ICP) in ocular point-of-care ultrasound (POCUS) images.  </li>
      </ul>"
   # https://vectorinstitute.ai
   # https://www.uhn.ca/
   # https://www.sickkids.ca/

  - company: "Columbia University"
    company_url: "https://hbil.bme.columbia.edu/"
    role: "Graduate Research Assistant"
    start: "Sep 2018"
    end: "Sep 2020"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> In order to have a better understanding of neonatal brain development, I implemented machine learning algorithms to segment different regions and tissues of an infant's brain. </li>
      <li> To improve MRI safety, I developed a novel algorithm to segment different tissues of whole-body using various MRI scan modalities, which can be used to track specific tissue temperature increases during MRI scan. </li>
    </ul>"

  - company: "Café Bazaar - Divar"
    company_url: "https://cafebazaar.ir/about?l=en"
    role: "Data Scientist"
    start: "Sep 2017"
    end: "Aug 2018"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Divar, is a classified-ad in Iran which is one of products of CafeBazaar.
      <li> To improve the relevancy of search results which leads to a better user experience, as the project owner, I developed an innovative search algorithm that utilizes semantic networks and word embedding.</li>
      <li> Refine user queries and optimize search filters for different categories to enhance the search experience by utilizing behavioral pattern analysis of unstructured data from user action logs. </li>
      <li> To assist human reviewers in finding duplicate listings and removing them from the platform, we developed a machine learning-based image search algorithm using Convolutional Neural Networks.</li>
      </ul>"



publication:
  - name: "ID-Seg: an infant deep learning-based segmentation framework to improve limbic structure estimates"
    authors: "Yun Wang*, <u>Fateme Sadat Haghpanah*</u>, Xuzhe Zhang, Katie Santamaria, Gabriela Koch da Costa Aguiar Alves, Elizabeth Bruno, Natalie Aw, Alexis Maddocks, Cristiane S Duarte, Catherine Monk, Andrew Laine, Jonathan Posner, program collaborators for Environmental influences on Child Health Outcomes"
    conference: "<strong>Brain Informatics Journal</strong>, December 2022 Dec;9(1):12."
    html_url: "https://link.springer.com/article/10.1186/s40708-022-00161-9"
    pdf: "https://link.springer.com/content/pdf/10.1186/s40708-022-00161-9.pdf?pdf=button"
    
  - name: "Groundhog: An Automated Accessibility Crawler for Mobile Apps"
    authors: "Navid Salehnamadi*, <u>Forough Mehralian*</u>, and Sam Malek"
    conference: "<strong>ASE 2022</strong>, 37th International Conference on Automated Software Engineering, October 2022"
    pdf: "https://seal.ics.uci.edu/publications/2022_ASE_Groundhog.pdf"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3551349.3556905"
  - name: "Data-driven Accessibility Repair Revisited: On the Effectiveness of Generating Labels for Icons in Android Apps"
    authors: "<u>Forough Mehralian</u>, Navid Salehnamadi, and Sam Malek"
    conference: "<strong>ESEC/FSE 2021</strong>, 29th ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering, August 2021"
    repo: "https://github.com/fmehralian/COALA"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3468264.3468604"
  - name: "Automated Construction of Energy Test Oracle for Android"
    authors: "Reyhaneh Jabbarvand, <u>Forough Mehralian</u>, and Sam Malek"
    conference: "<strong>ESEC/FSE 2020</strong>, 28th ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering, August 2020"
    repo: "https://github.com/seal-hub/ACETON"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3468264.3468604"

projects:
  - name: ACETON
    description: An LSTM model with attention mechanism to automatically generate energy test oracles for mobile apps.
    html_url: https://github.com/seal-hub/ACETON
    source: github

  - name: COALA
    description: A context-aware label generation model with encoder-decoder architecture to generate labels for unlabeld icons.
    html_url: https://github.com/fmehralian/COALA
    source: github

  - name: Oversight
    description: An accessibility service that automatically explores Android apps with and without TalkBack to find overly accessible elements.
    html_url: https://github.com/seal-hub/Oversight
    source: github

topics:
  - name: Java
  - name: Python
  - name: Machine Learning
