layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "Adventurous, nature-loving, curious, and always up for a new challenge and never afraid to push boundaries!"
about: "ABOUT ME"
email: ftm.haghpanah@gmail.com


social_media:
  linkedin: fateme-sadat-haghpanah-b2b59a90
  scholar: _QKNDs0AAAAJ&hl
  github: ftmhghpnh
  twitter: fatemehghpanah

  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of California, Irvine"
    company_url: "http://seal.ics.uci.edu"
    role: "Graduate Research Assistant"
    start: "Jun 2019"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Designed and implemented a suite of novel automated accessibility testing tools for Android apps, utilizing machine learning techniques, as well as static and dynamic analysis methods.</li>
      <li> Conducted extensive research into the use of image captioning for labeling unlabeled icons in Android apps, and identified a data-driven bias in the existing approach. Developed a novel deep learning solution, which significantly improved the quality of the generated labels.</li>
      <li> Designed and implemented a deep learning-based technique using PyTorch for building an oracle for energy tests. </li>
    </ul>"

  - company: "Candelis Inc."
    company_url: "https://www.candelis.com"
    role: "Software Engineer"
    start: "Jun 2021"
    end: "Sep 2022"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li>Designed and implemented the DICOMWeb standard, enabling web-based access to DICOM data. This involved developing the Store, Retrieve, and Query APIs as a new service.
 </li>
      <li> Implemented a cost-efficient archive and backup mechanism for the DICOM data using various Amazon S3 storage classes. This involved designing a data lifecycle management strategy and utilizing Amazon S3's Intelligent-Tiering and Glacier storage classes to optimize storage costs.</li>
      <li> Integrated Prometheus for time-series monitoring of key performance metrics, and utilized Grafana to visualize the data and gain insights into the system behavior. </li>
    </ul>"

  - company: "Café Bazaar"
    company_url: "https://cafebazaar.ir/about?l=en"
    role: "Software Engineer"
    start: "Jun 2018"
    end: "Aug 2018"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Developed a micro-service using Django for Bazaar, Iran's largest app store with over 40 million users, to display ads on their search page. Utilized Docker and Kubernetes for containerization and orchestration of the micro-service, respectively.</li>
      <li> Migrated the previous Redis database to PostgreSQL and optimized the queries to ensure improved performance and scalability.</li>
      <li> Implemented a Second-bid auction strategy for the advertisements and conducted beta testing of the service. </li>
    </ul>"



publication:
  - name: "Too Much Accessibility is Harmful! Automated Detection and Analysis of Overly Accessible Elements in Mobile Apps"
    authors: "<u>Forough Mehralian*</u>, Navid Salehnamadi*, Syed Fatiul Huq, and Sam Malek"
    conference: "<strong>ASE 2022</strong>, 37th International Conference on Automated Software Engineering, October 2022"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3551349.3560424"
    pdf: "https://seal.ics.uci.edu/publications/2022_ASE_Oversight.pdf"
  - name: "Groundhog: An Automated Accessibility Crawler for Mobile Apps"
    authors: "Navid Salehnamadi*, <u>Forough Mehralian*</u>, and Sam Malek"
    conference: "<strong>ASE 2022</strong>, 37th International Conference on Automated Software Engineering, October 2022"
    pdf: "https://seal.ics.uci.edu/publications/2022_ASE_Groundhog.pdf"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3551349.3556905"
  - name: "Data-driven Accessibility Repair Revisited: On the Effectiveness of Generating Labels for Icons in Android Apps"
    authors: "<u>Forough Mehralian</u>, Navid Salehnamadi, and Sam Malek"
    conference: "<strong>ESEC/FSE 2021</strong>, 29th ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering, August 2021"
    repo: "https://github.com/fmehralian/COALA"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3468264.3468604"
  - name: "Automated Construction of Energy Test Oracle for Android"
    authors: "Reyhaneh Jabbarvand, <u>Forough Mehralian</u>, and Sam Malek"
    conference: "<strong>ESEC/FSE 2020</strong>, 28th ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering, August 2020"
    repo: "https://github.com/seal-hub/ACETON"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3468264.3468604"

projects:
  - name: ACETON
    description: An LSTM model with attention mechanism to automatically generate energy test oracles for mobile apps.
    html_url: https://github.com/seal-hub/ACETON
    source: github

  - name: COALA
    description: A context-aware label generation model with encoder-decoder architecture to generate labels for unlabeld icons.
    html_url: https://github.com/fmehralian/COALA
    source: github

  - name: Oversight
    description: An accessibility service that automatically explores Android apps with and without TalkBack to find overly accessible elements.
    html_url: https://github.com/seal-hub/Oversight
    source: github

topics:
  - name: Java
  - name: Python
  - name: Machine Learning
