layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "I enjoy spending time in nature (for example star gazing, hiking, and kayaking), and constantly challenging myself to lift heavier weights with a barbell.!"
# acquiring new skills (currently playing piano), reading books, and discovering new music on Spotify!"
about: "I am Fateme, (/fɑ:te'me/), a M.Sc. student at the <a href=\"https://web.cs.toronto.edu/\">University of Toronto</a> and <a href=\"https://vectorinstitute.ai\">Vector Institute for Artificial Intelligence</a>, working with <a href=\"https://brudno.uhndata.io/\">Prof. Michael Brudno</a>. My research interests lie in developing practical solutions for the adoption of AI in real-world applications. During my masters, I focused on utilizing machine learning techniques to tackle healthcare challenges and identifying barriers that prevent the deployment of these algorithms in real-world settings."
email: ftm.haghpanah@gmail.com


social_media:
  linkedin: fateme-sadat-haghpanah-b2b59a90
  scholar: _QKNDs0AAAAJ&hl
  github: ftmhghpnh
  twitter: fatemehaghpanah

  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of Toronto"
    company_url: "https://web.cs.toronto.edu/"
    role: "Graduate Research Assistant"
    start: "Jan 2021"
    end: "May 2023"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Affiliated with, <a href=\"https://vectorinstitute.ai\">Vector Institute for Artificial Intelligence</a>, <a href=\"https://www.uhn.ca/\">University Health Network</a>, and <a href=\"https://www.sickkids.ca/\">SickKids, the Hospital for Children</a>.
    <li> Designed and developed a novel classification algorithm to detect cerebral microbleeds (CMB) in preterm infants' MRI scans, achieving over 90% precision and recall. The neural network model is the first-ever developed one for infant brain scans. </li>
    <li> Developed a supervised convolutional neural network model to expedite the diagnosis of brain tumors in children within hospital emergency rooms with the AUC ROC score of 0.95. </li>
    </ul>"

  - company: "Columbia University"
    company_url: "https://hbil.bme.columbia.edu/"
    role: "Graduate Research Assistant"
    start: "Sep 2018"
    end: "Sep 2020"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Implemented machine learning algorithms to segment distinct regions and tissues of neonatal brains, aiming to gain a better understanding of their development.</li>
      <li> Designed a novel neural network-based segmentation algorithm to enhance MRI safety by identifying various tissues of the entire body using different MRI scan modalities. </li>
</ul>"

  - company: "Café Bazaar - Divar"
    company_url: "https://cafebazaar.ir/about?l=en"
    role: "Data Scientist"
    start: "Sep 2017"
    end: "Aug 2018"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Divar, is a classified-ad in Iran which is one of products of CafeBazaar.
      <li> As the project owner, developed an innovative search algorithm that employs semantic networks and word embedding to enhance the relevancy of search results, ultimately leading to a better user experience.</li>
      <li> Utilized behavioral pattern analysis of unstructured data from user action logs to refine user queries and optimize search filters for various categories, resulting in an improved search experience. </li>
      <li> Developed a machine learning-based image search algorithm utilizing Convolutional Neural Networks to aid human reviewers in identifying and removing duplicate listings from the platform.</li>
      </ul>"



publication:
  - name: "Quantification of lung ventilation defects on hyperpolarized MRI: The Multi-Ethnic Study of Atherosclerosis (MESA) COPD study"
    authors: "Xuzhe Zhang, Elsa D Angelini, <u>Fateme S Haghpanah</u>, Andrew F Laine, Yanping Sun, Grant T Hiura, Stephen M Dashnaw, Martin R Prince, Eric A Hoffman, Bharath Ambale-Venkatesh, Joao A Lima, Jim M Wild, Emlyn W Hughes, R Graham Barr, Wei Shen"
    conference: "<strong>Magnetic Resonance Imaging Journal</strong>, October 2022, Volume 92, Pages 140-149."
    pdf: "https://www.sciencedirect.com/getaccess/pii/S0730725X22001102/purchase"
    html_url: "https://www.sciencedirect.com/science/article/abs/pii/S0730725X22001102"
    
  - name: "ID-Seg: an infant deep learning-based segmentation framework to improve limbic structure estimates"
    authors: "Yun Wang*, <u>Fateme Sadat Haghpanah*</u>, Xuzhe Zhang, Katie Santamaria, Gabriela Koch da Costa Aguiar Alves, Elizabeth Bruno, Natalie Aw, Alexis Maddocks, Cristiane S Duarte, Catherine Monk, Andrew Laine, Jonathan Posner, program collaborators for Environmental influences on Child Health Outcomes"
    conference: "<strong>Brain Informatics Journal</strong>, December 2022, Volume 9, Pages 1-12"
    html_url: "https://link.springer.com/article/10.1186/s40708-022-00161-9"
    repo: "https://github.com/wangyuncolumbia/ID-Seg"
    pdf: "https://link.springer.com/content/pdf/10.1186/s40708-022-00161-9.pdf?pdf=button"
    
  - name: "A transfer-learning approach for first-year developmental infant brain segmentation using deep neural networks"
    authors: "Yun Wang*, <u>Fateme Sadat Haghpanah*</u>, Natalie Aw, Andrew Laine, Jonathan Posner"
    conference: "<strong>bioRxiv</strong>, May 2021"
    pdf: "https://www.biorxiv.org/content/biorxiv/early/2020/05/25/2020.05.22.110619.full.pdf"
    html_url: "https://www.biorxiv.org/content/10.1101/2020.05.22.110619v1.full"
 

projects:
  - name: Neural Machine Translation (NMT)
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Implemented an encoder-decoder model with both single and multi-head attention mechanism to translate English to French using the Hansards dataset.
    </ul>"
    html_url: https://github.com/ftmhghpnh/Neural_Machine_Translation
    source: github
  
  - name: Causality in Medical Imaging
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Investigated the impact of causality on medical imaging by utilizing supervised machine learning algorithms to detect MRI acquisition parameters using the PPMI dataset, aiming to assess the potential improvement in performance.
    </ul>"
    html_url: https://github.com/ftmhghpnh/causality-in-PPMI-imaging-dataset
    source: github
    
  - name: Chest-Xray-Analysis
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Developed a deep neural network for automatic identification of chest diseases from X-ray images using machine learning.
    </ul>"
    html_url: https://github.com/ftmhghpnh/chest-xray-analysis
    source: github
    repo: https://github.com/ftmhghpnh/chest-xray-analysis

  - name: NYC house litigations analysis
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Developed a Shiny App for data visualization to explore potential inquiries about the public dataset on housing litigation in NYC. 
    </ul>"
    html_url: https://github.com/ftmhghpnh/fall2019-proj2--sec2-grp3
    source: github
   
  - name: A "data story" on the songs of our times
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Conducted a study on the lyrics of music from different genres using NLP techniques, including text preprocessing, data cleaning, topic modeling, and word embeddings like Word2vec.
    </ul>"
    html_url: https://github.com/ftmhghpnh/fall2019-proj1--ftmhghpnh
    source: github
    
  - name: Can you recognize the emotion from an image of a face?
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Created a facial emotion recognition classifier using feature extraction and selection techniques like HOG, SIFT, PCA, and landmark detection. Trained different classification models, including LDA, SVC, RandomForest, MLP, KNN, AdaBoost, and CNN-based approaches.
    </ul>"
    html_url: https://github.com/ftmhghpnh/fall2019-proj3-sec2--group6
    source: github
    
  - name: Algorithm implementation and evaluation, Collaborative Filtering
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Developed two collaborative filtering algorithms, Gradient Descent with Probabilistic Assumptions and Alternating Least Squares, from scratch. Subsequently, utilized Kernel Ridge Regression for post-processing the data.
    </ul>"
    html_url: https://github.com/ftmhghpnh/fall2019-project4-sec2-grp8
    source: github
   
  - name: Landmark Recognition Challenge
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Developed models for landmark recognition using HOG features and advanced neural network based classification models.
    </ul>"
    html_url: https://github.com/ftmhghpnh/fall2019-project5-sec2-grp4
    source: github

topics:
  - name: Python
  - name: Machine Learning
  - name: Deep Learning
  - name: Computer Vision
