layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "Adventurous, nature-loving, curious, and always up for a new challenge and never afraid to push boundaries."
about: "ABOUT ME, add menu on the left side and link them, figure out why my name is not in a row, and github icon for projects, and what to put in the news :-?"
email: ftm.haghpanah@gmail.com


social_media:
  linkedin: fateme-sadat-haghpanah-b2b59a90
  scholar: _QKNDs0AAAAJ&hl
  github: ftmhghpnh
  twitter: fatemehaghpanah

  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of Toronto"
    company_url: ""
    role: "Graduate Research Assistant"
    start: "Jan 2021"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Affiliated with , <a href=\"https://vectorinstitute.ai\">Vector Institute for Artificial Intelligence</a>, <a href=\"https://www.uhn.ca/\">University Health Network</a>, and <a href=\"https://www.sickkids.ca/\">SickKids, the Hospital for Children</a>.
      <li> To assist diagnosis of neurodevelopmental impairments, I developed  a generalized novel algorithm to detect cerebral microbleeds (CMB) in MRI modality from pre-term infants' brains. </li>
      <li> To expedite the diagnosis of brain tumors in children in hospital emergency rooms, where wait times can be lengthy, I developed a machine learning model for identifying signs of raised intracranial pressure (ICP) in ocular point-of-care ultrasound (POCUS) images.  </li>
      </ul>"
   # https://vectorinstitute.ai
   # https://www.uhn.ca/
   # https://www.sickkids.ca/

  - company: "Columbia University"
    company_url: "https://hbil.bme.columbia.edu/"
    role: "Graduate Research Assistant"
    start: "Sep 2018"
    end: "Sep 2020"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> In order to have a better understanding of neonatal brain development, I implemented machine learning algorithms to segment different regions and tissues of an infant's brain. </li>
      <li> To improve MRI safety, I developed a novel algorithm to segment different tissues of whole-body using various MRI scan modalities, which can be used to track specific tissue temperature increases during MRI scan. </li>
    </ul>"

  - company: "Café Bazaar - Divar"
    company_url: "https://cafebazaar.ir/about?l=en"
    role: "Data Scientist"
    start: "Sep 2017"
    end: "Aug 2018"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
    Divar, is a classified-ad in Iran which is one of products of CafeBazaar.
      <li> To improve the relevancy of search results which leads to a better user experience, as the project owner, I developed an innovative search algorithm that utilizes semantic networks and word embedding.</li>
      <li> Refine user queries and optimize search filters for different categories to enhance the search experience by utilizing behavioral pattern analysis of unstructured data from user action logs. </li>
      <li> To assist human reviewers in finding duplicate listings and removing them from the platform, we developed a machine learning-based image search algorithm using Convolutional Neural Networks.</li>
      </ul>"



publication:
  - name: "Quantification of lung ventilation defects on hyperpolarized MRI: The Multi-Ethnic Study of Atherosclerosis (MESA) COPD study"
    authors: "Xuzhe Zhang, Elsa D Angelini, <u>Fateme S Haghpanah</u>, Andrew F Laine, Yanping Sun, Grant T Hiura, Stephen M Dashnaw, Martin R Prince, Eric A Hoffman, Bharath Ambale-Venkatesh, Joao A Lima, Jim M Wild, Emlyn W Hughes, R Graham Barr, Wei Shen"
    conference: "<strong>Magnetic Resonance Imaging Journal</strong>, October 2022, Volume 92, Pages 140-149."
    pdf: "https://seal.ics.uci.edu/publications/2022_ASE_Groundhog.pdf"
    html_url: "https://dl.acm.org/doi/abs/10.1145/3551349.3556905"
    
  - name: "ID-Seg: an infant deep learning-based segmentation framework to improve limbic structure estimates"
    authors: "Yun Wang*, <u>Fateme Sadat Haghpanah*</u>, Xuzhe Zhang, Katie Santamaria, Gabriela Koch da Costa Aguiar Alves, Elizabeth Bruno, Natalie Aw, Alexis Maddocks, Cristiane S Duarte, Catherine Monk, Andrew Laine, Jonathan Posner, program collaborators for Environmental influences on Child Health Outcomes"
    conference: "<strong>Brain Informatics Journal</strong>, December 2022, Volume 9, Pages 1-12"
    html_url: "https://www.sciencedirect.com/science/article/abs/pii/S0730725X22001102?casa_token=hVc6IOb7YwEAAAAA:4cqAAdqRZ4nJfUfdy-_0Kwj-arsA3aOjFcXVNvJI9vPBcXQisDkA2yAsOEE5sE81_FP3Ni_4Qw"
    repo: "https://github.com/wangyuncolumbia/ID-Seg"
#   # pdf: ""
    
  - name: "A transfer-learning approach for first-year developmental infant brain segmentation using deep neural networks"
    authors: "Yun Wang*, <u>Fateme Sadat Haghpanah*</u>, Natalie Aw, Andrew Laine, Jonathan Posner"
    conference: "<strong>bioRxiv</strong>, May 2021"
    pdf: "https://www.biorxiv.org/content/biorxiv/early/2020/05/25/2020.05.22.110619.full.pdf"
    html_url: "https://www.biorxiv.org/content/10.1101/2020.05.22.110619v1.full"
 

projects:
  - name: Chest-Xray-Analysis
    description: In my project, I developed a deep neural network architecture to automatically identify important chest diseases from X-ray images, which is critical for screening, diagnosis and managing life-threatening diseases. This innovative approach has the potential to aid medical professionals in recognizing different diseases and improve patient outcomes. The performance of the model was evaluated against previous works, demonstrating comparable results.
    html_url: https://github.com/ftmhghpnh/chest-xray-analysis
    source: github

  - name: Causality in Medical Imaging
    description:  FILLL OUT
    html_url: https://github.com/ftmhghpnh/causality-in-PPMI-imaging-dataset
    source: github

  - name: Shiny App Development
    description: FILL OUT
    html_url: https://github.com/ftmhghpnh/fall2019-proj2--sec2-grp3
    source: github
   
  - name: A "data story" on the songs of our times
    description: FILL OUT
    html_url: https://github.com/ftmhghpnh/fall2019-proj2--sec2-grp3
    source: github
    
  - name: Shiny Can you recognize the emotion from an image of a face?
    description: FILL OUT
    html_url: https://github.com/ftmhghpnh/fall2019-proj3-sec2--group6
    source: github
    
  - name: Algorithm implementation and evaluation, Collaborative Filtering
    description: FILL OUT
    html_url: https://github.com/ftmhghpnh/fall2019-project4-sec2-grp8
    source: github
   
  - name: Landmark Recognition Challenge
    description: FILL OUT
    html_url: https://github.com/ftmhghpnh/fall2019-project5-sec2-grp4
    source: github

topics:
  - name: Python
  - name: Machine Learning
  - name: Deep Learning
  - name: Computer Vision
